### ISSUE TITLE
Compiling errors when using the command

### ISSUE THREAD

**Issue by WilliamWangPeng** [diharaw/GPUParticleSystem#1]
HI dear author,  
    It's truly a honor to write a letter to you,  I'm build your project nowadays and found the error when building as following, I wonder if there is a chance that you know the reason? :)

![image](https://user-images.githubusercontent.com/51076736/114118370-4f633300-991b-11eb-81a2-08040725518b.png)

thank you  
best regards to you  
William

**Comment by diharaw** [comment]
Since these are the same issues please avoid creating duplicate issues on other repositories. Thanks :)
